[package]
name = "wasm-playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk-common = { git = "https://github.com/breez/breez-sdk", branch = "savage-wasm-sdk-common" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
